import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    grade: {
        justifyContent: 'flex', 
        alignItems: 'center',
        margin: 2,
        marginBottom: 0,
    },
    itemgradelivre: {
        backgroundColor: 'rgba(76, 175, 80, 0.15)',
        borderColor: 'rgba(76, 175, 80, 0.5)',
        borderWidth: 1,
        fontSize: 14,
        color: '#333',
        padding: 5,
        borderRadius: 8,
        textAlign: 'center',
        width: 70,
    },
    itemgradeocupado: {
        backgroundColor: 'rgba(244, 67, 54, 0.15)',
        borderColor: 'rgba(244, 67, 54, 0.5)',
        borderWidth: 1,
        fontSize: 14,
        color: '#333',
        padding: 5,
        borderRadius: 8,
        textAlign: 'center',
        width: 70,
    },
    itemgradereservado: {
        backgroundColor: 'rgba(255, 193, 7, 0.15)',
        borderColor: 'rgba(255, 193, 7, 0.5)',
        borderWidth: 1,
        fontSize: 14,
        color: '#333',
        padding: 5,
        borderRadius: 8,
        textAlign: 'center',
        width: 70,
    },
    list : {
        justifyContent: 'space-between',
        height: '100%',
    },
    column: {
        height: 60,
        justifyContent: 'center',
        marginBottom: 0,
        marginLeft: 8,
        marginRight: 8,
        paddingVertical: 10,
    },
    detailsContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
});